import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createFixture, fakeHash } from './helpers/apps-script-fixture.mjs';

test('migration preserves old rows and headers and never selects the summary sheet', () => {
  const row = ['OLD-1', '2026-09-30', 'Dokter lama', 'Unit lama', 'Tindakan lama', 'Masalah lama', '', 'C1 - Critical'];
  const f = createFixture({ legacyRows: [row] });
  assert.deepEqual(f.data.data[1], row);
  assert.equal(f.data.data[0].length, 19);
  f.context.setupKomplainer();
  assert.equal(f.data.data[0].length, 19);
  const result = f.request({ action: 'list', ...f.adminSession });
  assert.equal(result.data[0].statusPenanganan, 'Baru');
  assert.equal(result.data[0].version, 1);
  assert.equal(f.properties.get('COMPLAINT_SHEET_NAME'), 'Data Komplain');
  f.context.generateWeeklySummary();
  assert.ok(f.ss.getSheetByName('Rekapan Mingguan'));
  assert.equal(f.request({ action: 'list', ...f.adminSession }).data[0].id, 'OLD-1');
  const pelapor = f.addUser('reporter@example.test');
  assert.equal(f.request({ action: 'list', ...pelapor }).data.length, 0);
});
test('unauthenticated and forged-role requests cannot access reports', () => {
  const f = createFixture();
  assert.equal(JSON.parse(f.context.doGet().text).code, 401);
  assert.equal(f.request({ action: 'list', apiKey: 'wrong' }).code, 403);
  assert.equal(f.request({ action: 'list', role: 'admin' }).code, 401);
  const a = f.addUser('a@example.test');
  const b = f.addUser('b@example.test');
  const item = f.createReport(a).data;
  assert.equal(f.request({ action: 'list', ...b, role: 'admin' }).data.length, 0);
  assert.equal(f.request({ action: 'detail', ...b, id: item.id }).code, 404);
  assert.equal(f.request({ action: 'delete', ...a, id: item.id, version: 1, role: 'admin' }).code, 403);
});
test('assignment, follow-up, completion and reopen enforce permissions and versions', () => {
  const f = createFixture();
  const reporter = f.addUser('reporter@example.test');
  const pic = f.addUser('pic@example.test', 'petugas');
  const other = f.addUser('other@example.test', 'petugas');
  let item = f.createReport(reporter).data;
  assert.equal(item.jalanKeluar, '');
  assert.equal(item.pelaporId, reporter.user.id);
  assert.equal(f.request({ action: 'assign', ...reporter, id: item.id, version: item.version, picId: pic.user.id }).code, 403);
  item = f.request({ action: 'assign', ...f.adminSession, id: item.id, version: item.version, picId: pic.user.id, tenggat: '2026-10-05' }).data;
  assert.equal(f.request({ action: 'list', ...pic }).data.length, 1);
  assert.equal(f.request({ action: 'list', ...other }).data.length, 0);
  assert.equal(f.request({ action: 'followUp', ...pic, id: item.id, version: 1, statusPenanganan: 'Selesai', jalanKeluar: 'Solusi', catatan: 'Selesai' }).code, 409);
  assert.equal(f.request({ action: 'followUp', ...pic, id: item.id, version: item.version, statusPenanganan: 'Selesai', jalanKeluar: '', catatan: 'Selesai' }).code, 400);
  item = f.request({ action: 'followUp', ...pic, id: item.id, version: item.version, statusPenanganan: 'Diproses', jalanKeluar: '', catatan: 'Mulai diperiksa' }).data;
  assert.equal(f.request({ action: 'update', ...reporter, ...item, tindakan: 'Perubahan' }).code, 403);
  item = f.request({ action: 'followUp', ...pic, id: item.id, version: item.version, statusPenanganan: 'Selesai', jalanKeluar: 'Masalah diperbaiki', catatan: 'Sudah diperiksa' }).data;
  assert.ok(item.selesaiPada);
  assert.equal(f.request({ action: 'reopen', ...pic, id: item.id, version: item.version, catatan: 'Masih bermasalah' }).code, 403);
  item = f.request({ action: 'reopen', ...reporter, id: item.id, version: item.version, catatan: 'Masalah muncul kembali' }).data;
  assert.equal(item.statusPenanganan, 'Baru');
  assert.equal(item.selesaiPada, '');
  const detail = f.request({ action: 'detail', ...reporter, id: item.id });
  assert.equal(detail.history.length, 5);
  assert.equal(detail.history[0].catatan, 'Masalah muncul kembali');
});
test('temporary password, revocation, last admin and active assignments are protected', () => {
  const f = createFixture();
  const result = f.request({ action: 'createUser', ...f.adminSession, nama: 'User', email: 'user@example.test', unit: 'Unit A', role: 'petugas', passwordHash: fakeHash });
  const temp = f.login(result.user.email);
  assert.equal(temp.user.mustChangePassword, true);
  assert.equal(f.request({ action: 'list', ...temp }).code, 403);
  assert.equal(f.request({ action: 'changePassword', ...temp, expectedHash: fakeHash, passwordHash: fakeHash }).status, 'success');
  assert.equal(f.request({ action: 'session', ...temp }).code, 401);
  const pic = f.login(result.user.email);
  const item = f.createReport(f.adminSession).data;
  f.request({ action: 'assign', ...f.adminSession, id: item.id, version: 1, picId: pic.user.id, tenggat: '' });
  assert.equal(f.request({ action: 'updateUser', ...f.adminSession, ...pic.user, role: 'pelapor', active: true }).code, 409);
  assert.equal(f.request({ action: 'updateUser', ...f.adminSession, ...f.admin, active: false }).code, 409);
  assert.equal(f.request({ action: 'bootstrap', nama: 'Another' }).code, 409);
  const users = f.request({ action: 'users', ...f.adminSession });
  assert.equal(JSON.stringify(users).includes('passwordHash'), false);
});
test('create retry is idempotent and spreadsheet formulas are escaped; archive preserves data', () => {
  const f = createFixture();
  const reporter = f.addUser('reporter@example.test');
  const requestId = randomUUID();
  const body = { requestId, komplain: '=IMPORTXML("https://example.test", "//x")', team: 'forged unit', statusPenanganan: 'Selesai', pelaporId: f.admin.id };
  const first = f.createReport(reporter, body).data;
  const second = f.createReport(reporter, body).data;
  assert.equal(first.id, second.id);
  assert.equal(f.request({ action: 'list', ...reporter }).data.length, 1);
  assert.equal(first.team, reporter.user.unit);
  assert.equal(first.statusPenanganan, 'Baru');
  assert.equal(first.pelaporId, reporter.user.id);
  assert.ok(f.data.data[1][5].startsWith("'="));
  assert.ok(first.komplain.startsWith('='));
  assert.equal(f.request({ action: 'delete', ...f.adminSession, id: first.id, version: 1 }).status, 'success');
  assert.equal(f.createReport(reporter, body).code, 409);
  assert.equal(f.request({ action: 'list', ...f.adminSession }).data.length, 0);
  assert.equal(f.data.getLastRow(), 2);
  assert.ok(f.data.data[1][17]);
});
test('authentication lookup is throttled and invalid dates are rejected', () => {
  const f = createFixture();
  for (let i = 0; i < 10; i++) assert.equal(f.request({ action: 'authLookup', email: 'admin@example.test' }).status, 'success');
  assert.equal(f.request({ action: 'authLookup', email: 'admin@example.test' }).code, 429);
  assert.equal(f.createReport(f.adminSession, { tanggal: '2026-02-30' }).code, 400);
});
