import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createFixture, fakeHash } from './helpers/apps-script-fixture.mjs';

test('migration preserves old rows and headers and never selects the summary sheet', () => {
  const row = ['OLD-1', '2026-09-30', 'Dokter lama', 'Unit lama', 'Tindakan lama', 'Masalah lama', '', 'C1 - Critical'];
  const f = createFixture({ legacyRows: [row] });
  assert.deepEqual(f.data.data[1], row);
  assert.equal(f.data.data[0].length, 20);
  f.context.setupKomplainer();
  assert.equal(f.data.data[0].length, 20);
  const result = f.request({ action: 'list', ...f.adminSession });
  assert.equal(result.data[0].statusPenanganan, 'Baru');
  assert.equal(result.data[0].version, 1);
  assert.equal(f.properties.get('COMPLAINT_SHEET_NAME'), 'Data Komplain');
  f.context.generateWeeklySummary();
  assert.ok(f.ss.getSheetByName('Rekapan Mingguan'));
  assert.equal(f.request({ action: 'list', ...f.adminSession }).data[0].id, 'OLD-1');
  const pelapor = f.addUser('reporter@example.test');
  assert.equal(f.request({ action: 'list', ...pelapor }).data.length, 0);
});
test('unauthenticated and forged-role requests cannot access reports', () => {
  const f = createFixture();
  assert.equal(JSON.parse(f.context.doGet().text).code, 401);
  assert.equal(f.request({ action: 'list', apiKey: 'wrong' }).code, 403);
  assert.equal(f.request({ action: 'list', role: 'admin' }).code, 401);
  const a = f.addUser('a@example.test');
  const b = f.addUser('b@example.test');
  const item = f.createReport(a).data;
  assert.equal(f.request({ action: 'list', ...b, role: 'admin' }).data.length, 0);
  assert.equal(f.request({ action: 'detail', ...b, id: item.id }).code, 404);
  assert.equal(f.request({ action: 'delete', ...a, id: item.id, version: 1, role: 'admin' }).code, 403);
});
test('assignment, follow-up, completion and reopen enforce permissions and versions', () => {
  const f = createFixture();
  const reporter = f.addUser('reporter@example.test');
  const pic = f.addUser('pic@example.test', 'petugas');
  const other = f.addUser('other@example.test', 'petugas');
  let item = f.createReport(reporter).data;
  assert.equal(item.jalanKeluar, '');
  assert.equal(item.pelaporId, reporter.user.id);
  assert.equal(f.request({ action: 'assign', ...reporter, id: item.id, version: item.version, picId: pic.user.id }).code, 403);
  item = f.request({ action: 'assign', ...f.adminSession, id: item.id, version: item.version, picId: pic.user.id, tenggat: '2026-10-05' }).data;
  assert.equal(f.request({ action: 'list', ...pic }).data.length, 1);
  assert.equal(f.request({ action: 'list', ...other }).data.length, 0);
  assert.equal(f.request({ action: 'followUp', ...pic, id: item.id, version: 1, statusPenanganan: 'Selesai', jalanKeluar: 'Solusi', catatan: 'Selesai' }).code, 409);
  assert.equal(f.request({ action: 'followUp', ...pic, id: item.id, version: item.version, statusPenanganan: 'Selesai', jalanKeluar: '', catatan: 'Selesai' }).code, 400);
  item = f.request({ action: 'followUp', ...pic, id: item.id, version: item.version, statusPenanganan: 'Diproses', jalanKeluar: '', catatan: 'Mulai diperiksa' }).data;
  assert.equal(f.request({ action: 'update', ...reporter, ...item, tindakan: 'Perubahan' }).code, 403);
  item = f.request({ action: 'followUp', ...pic, id: item.id, version: item.version, statusPenanganan: 'Selesai', jalanKeluar: 'Masalah diperbaiki', catatan: 'Sudah diperiksa' }).data;
  assert.ok(item.selesaiPada);
  assert.equal(f.request({ action: 'reopen', ...pic, id: item.id, version: item.version, catatan: 'Masih bermasalah' }).code, 403);
  item = f.request({ action: 'reopen', ...reporter, id: item.id, version: item.version, catatan: 'Masalah muncul kembali' }).data;
  assert.equal(item.statusPenanganan, 'Baru');
  assert.equal(item.selesaiPada, '');
  const detail = f.request({ action: 'detail', ...reporter, id: item.id });
  assert.equal(detail.history.length, 5);
  assert.equal(detail.history[0].catatan, 'Masalah muncul kembali');
});
test('temporary password, revocation, last admin and active assignments are protected', () => {
  const f = createFixture();
  const result = f.request({ action: 'createUser', ...f.adminSession, nama: 'User', email: 'user@example.test', unit: 'Unit A', role: 'petugas', passwordHash: fakeHash });
  const temp = f.login(result.user.email);
  assert.equal(temp.user.mustChangePassword, true);
  assert.equal(f.request({ action: 'list', ...temp }).code, 403);
  assert.equal(f.request({ action: 'changePassword', ...temp, expectedHash: fakeHash, passwordHash: fakeHash }).status, 'success');
  assert.equal(f.request({ action: 'session', ...temp }).code, 401);
  const pic = f.login(result.user.email);
  const item = f.createReport(f.adminSession).data;
  f.request({ action: 'assign', ...f.adminSession, id: item.id, version: 1, picId: pic.user.id, tenggat: '' });
  assert.equal(f.request({ action: 'updateUser', ...f.adminSession, ...pic.user, role: 'pelapor', active: true }).code, 409);
  assert.equal(f.request({ action: 'updateUser', ...f.adminSession, ...f.admin, active: false }).code, 409);
  assert.equal(f.request({ action: 'bootstrap', nama: 'Another' }).code, 409);
  const users = f.request({ action: 'users', ...f.adminSession });
  assert.equal(JSON.stringify(users).includes('passwordHash'), false);
});
test('create retry is idempotent and spreadsheet formulas are escaped; archive preserves data', () => {
  const f = createFixture();
  const reporter = f.addUser('reporter@example.test');
  const requestId = randomUUID();
  const body = { requestId, komplain: '=IMPORTXML("https://example.test", "//x")', team: 'Unit B', statusPenanganan: 'Selesai', pelaporId: f.admin.id };
  const first = f.createReport(reporter, body).data;
  const second = f.createReport(reporter, body).data;
  assert.equal(first.id, second.id);
  assert.equal(f.request({ action: 'list', ...reporter }).data.length, 1);
  assert.equal(first.team, 'Unit B');
  assert.equal(first.statusPenanganan, 'Baru');
  assert.equal(first.pelaporId, reporter.user.id);
  assert.ok(f.data.data[1][5].startsWith("'="));
  assert.ok(first.komplain.startsWith('='));
  assert.equal(f.request({ action: 'delete', ...f.adminSession, id: first.id, version: 1 }).status, 'success');
  assert.equal(f.createReport(reporter, body).code, 409);
  assert.equal(f.request({ action: 'list', ...f.adminSession }).data.length, 0);
  assert.equal(f.data.getLastRow(), 2);
  assert.ok(f.data.data[1][17]);
});
test('authentication lookup is throttled and invalid dates are rejected', () => {
  const f = createFixture();
  for (let i = 0; i < 10; i++) assert.equal(f.request({ action: 'authLookup', email: 'admin@example.test' }).status, 'success');
  assert.equal(f.request({ action: 'authLookup', email: 'admin@example.test' }).code, 429);
  assert.equal(f.createReport(f.adminSession, { tanggal: '2026-02-30' }).code, 400);
});

test('setup creates every sheet and seeds initial admin once without resetting accounts', async () => {
  const { verifyPassword } = await import('../src/lib/server/password.mjs');
  const f = createFixture();
  const users = f.ss.getSheetByName('Pengguna');
  users.data.splice(1);
  f.context.setupKomplainer();
  for (const name of ['Pengguna', 'Sesi', 'Riwayat', 'Rekapan Mingguan']) assert.ok(f.ss.getSheetByName(name).data[0].length);
  assert.equal(users.data[1][1], 'lambangws');
  assert.equal(users.data[1][2], 'lambangws');
  assert.equal(users.data[1][3], 'admin');
  assert.equal(users.data[1][8], true);
  assert.match(users.data[1][5], /^scrypt:[a-f0-9]{32}:[a-f0-9]{128}$/);
  if (process.env.TEST_INITIAL_ADMIN_PASSWORD) {
    assert.ok(await verifyPassword(process.env.TEST_INITIAL_ADMIN_PASSWORD, users.data[1][5]));
    assert.ok(!users.data[1].includes(process.env.TEST_INITIAL_ADMIN_PASSWORD));
  }
  const lookup = f.request({ action: 'authLookup', email: 'LAMBANGWS' });
  assert.equal(lookup.passwordHash, users.data[1][5]);
  const session = f.login('lambangws', lookup.passwordHash);
  assert.equal(f.request({ action: 'list', ...session }).code, 403);
  users.data[1][5] = fakeHash;
  users.data[1][8] = false;
  f.context.setupKomplainer();
  assert.equal(users.data.length, 2);
  assert.equal(users.data[1][5], fakeHash);
  assert.equal(users.data[1][8], false);
  users.data.splice(1);
  f.context.setupKomplainer();
  assert.equal(users.data.length, 1);
});

test('authenticated requests create missing sheets and extend legacy summary headers without erasing rows', () => {
  const f = createFixture();
  const summary = f.ss.getSheetByName('Rekapan Mingguan');
  summary.data[0] = summary.data[0].slice(0, 6);
  const old = ['2026-09-28', 1, 0, 0, 1, 0];
  summary.appendRow(old);
  f.ss.getSheets().splice(f.ss.getSheets().findIndex((sheet) => sheet.name === 'Riwayat'), 1);
  assert.equal(f.request({ action: 'session', ...f.adminSession }).status, 'success');
  assert.ok(f.ss.getSheetByName('Riwayat'));
  assert.equal(summary.data[0].length, 12);
  assert.deepEqual(summary.data[1], old);
  f.properties.set('COMPLAINT_SHEET_NAME', 'Komplain Baru');
  f.context.ensureSchema();
  assert.equal(f.ss.getSheetByName('Komplain Baru').data[0].length, 20);
  f.data.maxColumns = 8;
  f.context.ensureHeaders(f.data);
  assert.equal(f.data.maxColumns, 20);
  const users = f.ss.getSheetByName('Pengguna');
  users.data[0] = users.data[0].slice(0, 8);
  users.data[1] = users.data[1].slice(0, 8);
  f.context.ensureSchema();
  assert.equal(users.data[0].length, 9);
});

test('setup generates missing or short API key and preserves a valid key on rerun', () => {
  const f = createFixture();
  f.properties.delete('APP_API_KEY');
  f.context.setupKomplainer();
  const generated = f.properties.get('APP_API_KEY');
  assert.match(generated, /^[a-f0-9]{64}$/);
  f.context.setupKomplainer();
  assert.equal(f.properties.get('APP_API_KEY'), generated);
  f.properties.set('APP_API_KEY', 'short');
  f.context.setupKomplainer();
  assert.match(f.properties.get('APP_API_KEY'), /^[a-f0-9]{64}$/);
  assert.notEqual(f.properties.get('APP_API_KEY'), generated);
});

test('admin delegates a case to a reporter without granting global access or changing role', async () => {
  const { canFollowUp } = await import('../src/app/komplain/workflow.mjs');
  const f = createFixture();
  const owner = f.addUser('owner@example.test');
  const delegate = f.addUser('delegate@example.test');
  const other = f.addUser('other@example.test');
  let item = f.createReport(owner).data;
  const unrelated = f.createReport(owner).data;
  assert.equal(f.request({ action: 'list', ...delegate }).data.length, 0);
  assert.ok(f.request({ action: 'list', ...f.adminSession }).assignees.some((user) => user.id === delegate.user.id));
  assert.equal(f.request({ action: 'assign', ...delegate, id: item.id, version: 1, picId: delegate.user.id }).code, 404);
  item = f.request({ action: 'assign', ...f.adminSession, id: item.id, version: 1, picId: delegate.user.id }).data;
  assert.equal(item.picRole, 'pelapor');
  assert.equal(item.pelaporRole, 'pelapor');
  const delegatedRow = f.request({ action: 'list', ...delegate }).data[0];
  assert.equal(delegatedRow.picRole, 'pelapor');
  assert.equal('passwordHash' in delegatedRow, false);
  assert.equal(f.request({ action: 'session', ...delegate }).user.role, 'pelapor');
  assert.equal(f.request({ action: 'list', ...delegate }).data.length, 1);
  assert.equal(f.request({ action: 'detail', ...delegate, id: unrelated.id }).code, 404);
  assert.equal(f.request({ action: 'followUp', ...owner, id: item.id, version: item.version, statusPenanganan: 'Diproses', catatan: 'Bukan PIC' }).code, 403);
  assert.equal(canFollowUp(item, delegate.user), true);
  assert.equal(canFollowUp(item, other.user), false);
  assert.equal(f.request({ action: 'followUp', ...other, id: item.id, version: item.version, statusPenanganan: 'Diproses', catatan: 'Tidak berwenang' }).code, 404);
  assert.equal(f.request({ action: 'updateUser', ...f.adminSession, ...delegate.user, active: false }).code, 409);
  item = f.request({ action: 'followUp', ...delegate, id: item.id, version: item.version, statusPenanganan: 'Diproses', catatan: 'Diperiksa' }).data;
  assert.equal(item.statusPenanganan, 'Diproses');
  item = f.request({ action: 'assign', ...f.adminSession, id: item.id, version: item.version, picId: other.user.id }).data;
  assert.equal(f.request({ action: 'detail', ...delegate, id: item.id }).code, 404);
  assert.equal(f.request({ action: 'followUp', ...delegate, id: item.id, version: item.version, statusPenanganan: 'Selesai', jalanKeluar: 'Solusi', catatan: 'Selesai' }).code, 404);
  item = f.request({ action: 'followUp', ...other, id: item.id, version: item.version, statusPenanganan: 'Selesai', jalanKeluar: 'Sudah diperbaiki', catatan: 'Selesai' }).data;
  assert.equal(item.statusPenanganan, 'Selesai');
});


test('reporter can set and edit a report team without changing account unit or access', () => {
  const f = createFixture();
  const reporter = f.addUser('reporter@example.test');
  const other = f.addUser('other@example.test');
  assert.equal(f.createReport(reporter, { team: '   ' }).code, 400);
  assert.equal(f.createReport(reporter, { team: 'x'.repeat(201) }).code, 400);
  let item = f.createReport(reporter, { team: '  Unit Baru  ' }).data;
  assert.equal(item.team, 'Unit Baru');
  item = f.request({ action: 'update', ...reporter, ...item, team: 'Unit Revisi' }).data;
  assert.equal(item.team, 'Unit Revisi');
  assert.equal(f.request({ action: 'session', ...reporter }).user.unit, 'Unit A');
  assert.equal(f.request({ action: 'list', ...other }).data.length, 0);
  assert.equal(f.request({ action: 'update', ...other, ...item, team: 'Unit Lain' }).code, 404);
});

test('hospital persists through create, edit and follow-up and old clients preserve it', () => {
  const f = createFixture();
  let item = f.createReport(f.adminSession, { rumahSakit: 'RS Harapan' }).data;
  assert.equal(item.rumahSakit, 'RS Harapan');
  assert.equal(f.data.data[0][19], 'Rumah Sakit');
  assert.equal(f.data.data[1][19], 'RS Harapan');
  item = f.request({ ...item, ...f.adminSession, action: 'update', rumahSakit: 'RS Sehat' }).data;
  assert.equal(item.rumahSakit, 'RS Sehat');
  const oldBody = { ...item };
  delete oldBody.rumahSakit;
  item = f.request({ ...oldBody, ...f.adminSession, action: 'update' }).data;
  assert.equal(item.rumahSakit, 'RS Sehat');
  const pic = f.addUser('hospital-pic@example.test', 'petugas');
  item = f.request({ ...f.adminSession, action: 'assign', id: item.id, version: item.version, picId: pic.user.id }).data;
  item = f.request({ ...pic, action: 'followUp', id: item.id, version: item.version, statusPenanganan: 'Selesai', jalanKeluar: 'Alat diganti dan diuji', catatan: 'Verifikasi selesai' }).data;
  assert.equal(item.rumahSakit, 'RS Sehat');
  assert.equal(item.jalanKeluar, 'Alat diganti dan diuji');
  assert.equal(f.request({ ...f.adminSession, action: 'detail', id: item.id }).data.rumahSakit, 'RS Sehat');
});

test('existing nineteen-column sheet gains hospital header without shifting report data', () => {
  const f = createFixture();
  const created = f.createReport(f.adminSession).data;
  f.data.data[0].pop();
  f.data.data[1].pop();
  const original = [...f.data.data[1]];
  const result = f.request({ ...f.adminSession, action: 'detail', id: created.id });
  assert.equal(result.status, 'success');
  assert.deepEqual(f.data.data[1], original);
  assert.equal(f.data.data[0][19], 'Rumah Sakit');
  assert.equal(result.data.rumahSakit, '');
  assert.equal(result.data.version, created.version);
});
