'use client';
import { PlusCircle, ChevronRight } from 'lucide-react';
import WorkflowBadge from './workflow-badge';
import { InlineText } from './formatted-text';
import { handlingStatus, isOverdue, canFollowUp } from './workflow.mjs';

const button = 'inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400 disabled:opacity-50';
export default function HomePanel({ list, user, loaded, busy, today, formatDate, onCreate, onOpen, onReports, onRecap, onUsers, onAssign, onFollowUp }) {
  const own = list.filter((item) => !item.restricted && (user.role === 'admin' || item.picId === user.id || item.pelaporId === user.id));
  const active = own.filter((item) => handlingStatus(item) !== 'Selesai');
  const attention = active.filter((item) => user.role === 'admin' ? !item.picId || isOverdue(item, today) : item.picId === user.id);
  const priority = [...attention].sort((a, b) => Number(isOverdue(b, today)) - Number(isOverdue(a, today)) || (a.tenggat || '9999').localeCompare(b.tenggat || '9999'));
  const displayed = new Set(priority.slice(0, 3).map((item) => item.id));
  const latest = [...own.filter((item) => !displayed.has(item.id))].sort((a, b) => String(b.createdAt || b.tanggal || '').localeCompare(String(a.createdAt || a.tanggal || ''))).slice(0, 3);
  const openSection = (title, items, actionable = false) => <section className="space-y-3" aria-label={title}><h3 className="font-semibold">{title}</h3>{!loaded ? <p className="text-sm text-slate-400">Menunggu data laporan…</p> : !items.length ? <p className="rounded-xl border border-dashed border-slate-700 p-4 text-sm text-slate-400">{actionable ? 'Tidak ada laporan yang perlu tindakan Anda saat ini.' : own.length ? 'Laporan lainnya sudah tampil pada bagian perlu tindakan.' : 'Belum ada laporan. Mulai dengan membuat laporan baru.'}</p> : <div className="divide-y divide-slate-800 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900">{items.map((item) => <div key={item.id} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="break-words text-sm font-semibold">{item.dokter || 'Dokter belum diisi'}</p><p className="mt-1 break-words text-xs text-slate-400">{item.rumahSakit || 'Rumah sakit belum diisi'}</p></div><WorkflowBadge status={handlingStatus(item)} /></div><p className="mt-2 line-clamp-2 break-words text-sm text-slate-300"><InlineText text={item.komplain || 'Deskripsi belum diisi'} /></p><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><p className={`min-w-0 break-words text-xs ${isOverdue(item, today) ? 'text-amber-300' : 'text-slate-400'}`}>{actionable ? !item.picId ? 'Perlu penanggung jawab' : item.tenggat ? `${isOverdue(item, today) ? 'Lewat tenggat' : 'Tenggat'}: ${formatDate(item.tenggat)}` : 'Menunggu tindak lanjut Anda' : `PIC: ${item.picNama || 'Belum ditugaskan'}`}</p><button disabled={busy} onClick={() => actionable && user.role === 'admin' && !item.picId ? onAssign(item) : actionable && canFollowUp(item, user) ? onFollowUp(item) : onOpen(item)} className={`${button} shrink-0 bg-slate-800 text-blue-300`}>{actionable && user.role === 'admin' && !item.picId ? 'Tentukan PIC' : actionable && canFollowUp(item, user) ? 'Catat perkembangan' : handlingStatus(item) === 'Selesai' ? 'Lihat penyelesaian' : 'Lihat detail'}<ChevronRight aria-hidden="true" className="h-4 w-4" /></button></div></div>)}</div>}</section>;
  return <div className="space-y-6"><section className="rounded-2xl border border-slate-800 bg-slate-900 p-4 sm:p-5"><p className="text-sm text-slate-400">Halo, {user.nama || 'selamat datang'}</p><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold">{user.role === 'admin' ? 'Pantau laporan dan penanganan' : user.role === 'petugas' ? 'Tugas Anda hari ini' : 'Ada kendala di lapangan?'}</h2><p className="mt-1 text-sm text-slate-400">{user.role === 'pelapor' ? 'Laporkan masalah dan pantau perkembangannya di sini.' : 'Prioritaskan laporan yang membutuhkan tindakan Anda.'}</p></div><button disabled={busy} onClick={onCreate} className={`${button} bg-blue-600 text-white hover:bg-blue-500`}><PlusCircle aria-hidden="true" className="h-4 w-4" />Buat laporan baru</button></div><div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-slate-800 pt-3"><p role="status" className="text-sm text-slate-300">{loaded ? `${active.length} laporan belum selesai · ${attention.length} perlu tindakan Anda` : 'Memuat ringkasan…'}</p><button disabled={busy} onClick={onRecap} className={`${button} text-blue-300`}>Lihat rekap<ChevronRight aria-hidden="true" className="h-4 w-4" /></button></div></section>{openSection('Perlu tindakan Anda', priority.slice(0, 3), true)}{attention.length > 3 && <p className="text-xs text-slate-400">Menampilkan 3 dari {attention.length} laporan. Lihat daftar laporan untuk lainnya.</p>}{openSection(user.role === 'admin' ? 'Laporan terbaru' : 'Laporan saya terbaru', latest)}<div className="flex flex-wrap gap-2"><button disabled={busy} onClick={onReports} className={`${button} bg-slate-800`}>Lihat semua laporan<ChevronRight aria-hidden="true" className="h-4 w-4" /></button>{user.role === 'admin' && <button disabled={busy} onClick={onUsers} className={`${button} text-blue-300`}>Kelola akun & persetujuan</button>}</div></div>;
}
